### ISSUE TITLE
Errors with install on Zbx 4.4

### ISSUE THREAD

**Issue by charweb** [elekgeek/zabbix#1]
1. Brocade Foundry performance install said "Memory utilization" is already used. I edited xml to rename to Brocade Memory Utilization" and worked fine. 
2. After installing 2 generic modules and performance module I try to install the stackable  module and get the following error.
"Details Cannot update host
Template cannot be linked to another template more than once even through other templates."
The host currently has only the following modules associated with it.

Template Module Brocade_Foundry Performance SNMPv3 | UnlinkUnlink and clear

Template Module Generic SNMPv3 | UnlinkUnlink and clear
Template Module Interfaces SNMPv3 | UnlinkUnlink and clear

I had other cisco snmpv2 modules installed but not linked, i have now removed them. I still have the link error above.

**Comment by elekgeek** [comment]
you shouldn't have renamed the performance template, it's name is found in the linked modules the main stackable template, and now it can not find it, remove performance template and link the one renamed for a start.  You had to investigate the first issue because it shouldn't complain about the memory utilization app in the performance template, you might have conflicts some where, 

I will setup a brand new zabbix, import the first 3 templates then import the stackable template to see what happens, though I have it already running 9n production zabbix with more than 90 hosts without any issues.

**Comment by elekgeek** [comment]
I have successfully imported those templates into a brand new zabbix appliance. I don't see any issues, the issues are  on your box, you need to solve them.
